name: autofix.ci

on:
    pull_request:
    push:
        branches: ['main']

permissions:
    contents: read

jobs:
    autofix:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install pnpm
              uses: pnpm/action-setup@v2

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: pnpm install

            - name: Fix lint issues
              run: pnpm lint:fix

            - uses: autofix-ci/action@bee19d72e71787c12ca0f29de72f2833e437e4c9
              with:
                  commit-message: 'chore: apply automated lint fixes'
