name: ci

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: pnpm install

            - name: Lint
              run: pnpm lint

            - name: Build
              run: pnpm build

            - name: Test
              run: pnpm coverage

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
